"""
review_api.py — human review layer for the matching engine.

SETUP
  pip install fastapi uvicorn
  python add_review_columns.py   (run once first)
  uvicorn review_api:app --reload

Then open http://127.0.0.1:8000/docs for interactive API docs (free,
auto-generated by FastAPI from the route definitions below).

ENDPOINTS
  GET  /health
  GET  /matches                 list matches, filterable by guard_decision/category/reviewed
  GET  /matches/{match_id}      full detail for one match (joined with image + post info)
  POST /matches/{match_id}/review   record a human decision on a match
  GET  /images/{image_id}/matches   all posts scored against one image, best first

DESIGN NOTE: the human review never overwrites guard_decision/guard_reason
— those stay exactly as the automated guard produced them. The human's
call goes into separate human_decision/human_note/reviewed_at columns,
so a reviewer can override a guard rejection (or reject something the
guard approved) while the original automated reasoning stays fully
visible and auditable, same principle as the rest of this pipeline.
"""

import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel

DB_PATH = Path("data/pipeline.db")

app = FastAPI(
    title="Image-Content Matching Review API",
    description="Human review layer for guard-flagged image/blog-post matches.",
    version="1.0.0",
)


def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


class ReviewRequest(BaseModel):
    decision: str          # "approved" or "rejected"
    note: Optional[str] = None


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/matches")
def list_matches(
    guard_decision: Optional[str] = Query(None, description="Filter: 'approved' or 'rejected'"),
    category: Optional[str] = Query(None, description="Filter by image category, e.g. 'fox'"),
    reviewed: Optional[bool] = Query(None, description="True = only human-reviewed rows, False = only unreviewed"),
    limit: int = Query(50, le=500),
):
    conn = get_conn()
    query = """
        SELECT m.id, m.image_id, m.post_id, m.similarity, m.guard_decision,
               m.guard_reason, m.human_decision, m.human_note, m.reviewed_at,
               i.filepath, i.category, i.caption, p.title AS post_title
        FROM matches m
        JOIN images i ON m.image_id = i.id
        JOIN blog_posts p ON m.post_id = p.id
        WHERE 1=1
    """
    params = []

    if guard_decision:
        query += " AND m.guard_decision = ?"
        params.append(guard_decision)
    if category:
        query += " AND i.category = ?"
        params.append(category)
    if reviewed is True:
        query += " AND m.human_decision IS NOT NULL"
    elif reviewed is False:
        query += " AND m.human_decision IS NULL"

    query += " ORDER BY m.similarity DESC LIMIT ?"
    params.append(limit)

    rows = conn.execute(query, params).fetchall()
    conn.close()
    return [dict(r) for r in rows]


@app.get("/matches/{match_id}")
def get_match(match_id: str):
    conn = get_conn()
    row = conn.execute(
        """
        SELECT m.*, i.filepath, i.category, i.caption, i.conf_category, i.conf_caption,
               p.title AS post_title, p.body AS post_body, p.expected_category
        FROM matches m
        JOIN images i ON m.image_id = i.id
        JOIN blog_posts p ON m.post_id = p.id
        WHERE m.id = ?
        """,
        (match_id,),
    ).fetchone()
    conn.close()

    if row is None:
        raise HTTPException(status_code=404, detail=f"No match found with id {match_id}")
    return dict(row)


@app.post("/matches/{match_id}/review")
def review_match(match_id: str, review: ReviewRequest):
    if review.decision not in ("approved", "rejected"):
        raise HTTPException(status_code=400, detail="decision must be 'approved' or 'rejected'")

    conn = get_conn()
    existing = conn.execute("SELECT id FROM matches WHERE id = ?", (match_id,)).fetchone()
    if existing is None:
        conn.close()
        raise HTTPException(status_code=404, detail=f"No match found with id {match_id}")

    conn.execute(
        "UPDATE matches SET human_decision = ?, human_note = ?, reviewed_at = ? WHERE id = ?",
        (review.decision, review.note, datetime.now(timezone.utc).isoformat(), match_id),
    )
    conn.commit()

    updated = conn.execute(
        "SELECT id, guard_decision, guard_reason, human_decision, human_note, reviewed_at "
        "FROM matches WHERE id = ?",
        (match_id,),
    ).fetchone()
    conn.close()
    return dict(updated)


@app.get("/images/{image_id}/matches")
def matches_for_image(image_id: str, include_rejected: bool = False):
    conn = get_conn()
    image = conn.execute("SELECT * FROM images WHERE id = ?", (image_id,)).fetchone()
    if image is None:
        conn.close()
        raise HTTPException(status_code=404, detail=f"No image found with id {image_id}")

    query = """
        SELECT m.id, m.post_id, m.similarity, m.guard_decision, m.guard_reason,
               m.human_decision, p.title AS post_title
        FROM matches m
        JOIN blog_posts p ON m.post_id = p.id
        WHERE m.image_id = ?
    """
    params = [image_id]
    if not include_rejected:
        query += " AND m.guard_decision = 'approved'"
    query += " ORDER BY m.similarity DESC"

    rows = conn.execute(query, params).fetchall()
    conn.close()

    return {
        "image": dict(image),
        "matches": [dict(r) for r in rows],
    }
